/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidatorOperatorAddressRouteImport } from './routes/validator.$operatorAddress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorOperatorAddressRoute =
  ValidatorOperatorAddressRouteImport.update({
    id: '/validator/$operatorAddress',
    path: '/validator/$operatorAddress',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/validator/$operatorAddress': typeof ValidatorOperatorAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/validator/$operatorAddress': typeof ValidatorOperatorAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/validator/$operatorAddress': typeof ValidatorOperatorAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/validator/$operatorAddress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/validator/$operatorAddress'
  id: '__root__' | '/' | '/validator/$operatorAddress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValidatorOperatorAddressRoute: typeof ValidatorOperatorAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator/$operatorAddress': {
      id: '/validator/$operatorAddress'
      path: '/validator/$operatorAddress'
      fullPath: '/validator/$operatorAddress'
      preLoaderRoute: typeof ValidatorOperatorAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValidatorOperatorAddressRoute: ValidatorOperatorAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
